spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/icatch
    url: jdbc:mysql://localhost:3306/db25104?serverTimezone=Asia/Seoul
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbid251 #root
    password: dbpass251  #chltjfbs23!


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영 환경에서는 validate 권장
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        connection:
          characterEncoding: utf8
          charSet: utf8
          useUnicode: true
  sql:
    init:
      mode: always

security:
  jwt:
    token:
      secret: a37sdl28ydh38gsl39syw72jsk10pq59asd48fg123hj89klw4ert41yu1io123456789
      secret-key: a37sdl28ydh38gsl39syw72jsk10pq59asd48fg123hj89klw4ert41yu1io123456789
      expire-length: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.example.icatch: DEBUG  # 프로젝트 패키지명으로 변경하세요

server:
  port: 60004